import { Injectable } from '@angular/core';
import { Observable,of } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class Service {
  data_project(): Observable<any> {
    return of([
      {
        id:1,
        image: 'https://picsum.photos/seed/project1/400/300',
        name: 'Project Alpha',
        status: 'succeed',
        date: '2025-07-22',
        size: '150kb',
        owner: 'admin@gmail.com',
        number_img: 25,
        iso: 104,
        img_discription: 'ภาพถ่ายผลิตภัณฑ์สำหรับแคมเปญฤดูร้อน',
      },
      {
        id:2,
        image: 'https://picsum.photos/seed/project2/400/300',
        name: 'Project Beta',
        status: 'error',
        date: '2025-07-21',
        size: '110kb',
        owner: 'admin@gmail.com',
        number_img: 10,
        iso: 104,
        img_discription: 'ภาพถ่ายสถาปัตยกรรมภายในอาคารสำนักงาน',
      },
      {
        id:3,
        image: 'https://picsum.photos/seed/project3/400/300',
        name: 'Project Gamma',
        status: 'fix',
        date: '2025-07-20',
        size: '180kb',
        owner: 'admin@gmail.com',
        number_img: 40,
        iso: 104,
        img_discription: 'ภาพถ่ายบุคคลสำหรับโปรไฟล์ทีม',
      },
      {
        image: 'https://picsum.photos/seed/project4/400/300',
        name: 'Project Delta',
        status: 'async',
        date: '2025-07-19',
        size: '95kb',
        owner: 'admin@gmail.com',
        number_img: 18,
        iso: 104,
        img_discription: 'ภาพถ่ายทิวทัศน์จากโดรน',
      },
      {
        image: 'https://picsum.photos/seed/project5/400/300',
        name: 'Project Epsilon',
        status: 'succeed',
        date: '2025-07-18',
        size: '210kb',
        owner: 'admin@gmail.com',
        number_img: 55,
        iso: 104,
        img_discription: 'ภาพถ่ายอีเวนต์เปิดตัวสินค้าใหม่',
      },
      {
        image: 'https://picsum.photos/seed/project6/400/300',
        name: 'Project Zeta',
        status: 'succeed',
        date: '2025-07-17',
        size: '130kb',
        owner: 'admin@gmail.com',
        number_img: 30,
        iso: 104,
        img_discription: 'ภาพถ่ายอาหารสำหรับเมนูร้านอาหาร',
      },
      {
        image: 'https://picsum.photos/seed/project7/400/300',
        name: 'Project Eta',
        status: 'error',
        date: '2025-07-16',
        size: '145kb',
        owner: 'admin@gmail.com',
        number_img: 22,
        iso: 104,
        img_discription: 'ภาพถ่ายมาโครของส่วนประกอบอิเล็กทรอนิกส์',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
      {
        image: 'https://picsum.photos/seed/project1/400/300',
        name: 'Project Alpha',
        status: 'succeed',
        date: '2025-07-22',
        size: '150kb',
        owner: 'admin@gmail.com',
        number_img: 25,
        iso: 104,
        img_discription: 'ภาพถ่ายผลิตภัณฑ์สำหรับแคมเปญฤดูร้อน',
      },
      {
        image: 'https://picsum.photos/seed/project2/400/300',
        name: 'Project Beta',
        status: 'error',
        date: '2025-07-21',
        size: '110kb',
        owner: 'admin@gmail.com',
        number_img: 10,
        iso: 104,
        img_discription: 'ภาพถ่ายสถาปัตยกรรมภายในอาคารสำนักงาน',
      },
      {
        image: 'https://picsum.photos/seed/project3/400/300',
        name: 'Project Gamma',
        status: 'fix',
        date: '2025-07-20',
        size: '180kb',
        owner: 'admin@gmail.com',
        number_img: 40,
        iso: 104,
        img_discription: 'ภาพถ่ายบุคคลสำหรับโปรไฟล์ทีม',
      },
      {
        image: 'https://picsum.photos/seed/project4/400/300',
        name: 'Project Delta',
        status: 'async',
        date: '2025-07-19',
        size: '95kb',
        owner: 'admin@gmail.com',
        number_img: 18,
        iso: 104,
        img_discription: 'ภาพถ่ายทิวทัศน์จากโดรน',
      },
      {
        image: 'https://picsum.photos/seed/project5/400/300',
        name: 'Project Epsilon',
        status: 'succeed',
        date: '2025-07-18',
        size: '210kb',
        owner: 'admin@gmail.com',
        number_img: 55,
        iso: 104,
        img_discription: 'ภาพถ่ายอีเวนต์เปิดตัวสินค้าใหม่',
      },
      {
        image: 'https://picsum.photos/seed/project6/400/300',
        name: 'Project Zeta',
        status: 'succeed',
        date: '2025-07-17',
        size: '130kb',
        owner: 'admin@gmail.com',
        number_img: 30,
        iso: 104,
        img_discription: 'ภาพถ่ายอาหารสำหรับเมนูร้านอาหาร',
      },
      {
        image: 'https://picsum.photos/seed/project7/400/300',
        name: 'Project Eta',
        status: 'error',
        date: '2025-07-16',
        size: '145kb',
        owner: 'admin@gmail.com',
        number_img: 22,
        iso: 104,
        img_discription: 'ภาพถ่ายมาโครของส่วนประกอบอิเล็กทรอนิกส์',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
      {
        image: 'https://picsum.photos/seed/project1/400/300',
        name: 'Project Alpha',
        status: 'succeed',
        date: '2025-07-22',
        size: '150kb',
        owner: 'admin@gmail.com',
        number_img: 25,
        iso: 104,
        img_discription: 'ภาพถ่ายผลิตภัณฑ์สำหรับแคมเปญฤดูร้อน',
      },
      {
        image: 'https://picsum.photos/seed/project2/400/300',
        name: 'Project Beta',
        status: 'error',
        date: '2025-07-21',
        size: '110kb',
        owner: 'admin@gmail.com',
        number_img: 10,
        iso: 104,
        img_discription: 'ภาพถ่ายสถาปัตยกรรมภายในอาคารสำนักงาน',
      },
      {
        image: 'https://picsum.photos/seed/project3/400/300',
        name: 'Project Gamma',
        status: 'fix',
        date: '2025-07-20',
        size: '180kb',
        owner: 'admin@gmail.com',
        number_img: 40,
        iso: 104,
        img_discription: 'ภาพถ่ายบุคคลสำหรับโปรไฟล์ทีม',
      },
      {
        image: 'https://picsum.photos/seed/project4/400/300',
        name: 'Project Delta',
        status: 'async',
        date: '2025-07-19',
        size: '95kb',
        owner: 'admin@gmail.com',
        number_img: 18,
        iso: 104,
        img_discription: 'ภาพถ่ายทิวทัศน์จากโดรน',
      },
      {
        image: 'https://picsum.photos/seed/project5/400/300',
        name: 'Project Epsilon',
        status: 'succeed',
        date: '2025-07-18',
        size: '210kb',
        owner: 'admin@gmail.com',
        number_img: 55,
        iso: 104,
        img_discription: 'ภาพถ่ายอีเวนต์เปิดตัวสินค้าใหม่',
      },
      {
        image: 'https://picsum.photos/seed/project6/400/300',
        name: 'Project Zeta',
        status: 'succeed',
        date: '2025-07-17',
        size: '130kb',
        owner: 'admin@gmail.com',
        number_img: 30,
        iso: 104,
        img_discription: 'ภาพถ่ายอาหารสำหรับเมนูร้านอาหาร',
      },
      {
        image: 'https://picsum.photos/seed/project7/400/300',
        name: 'Project Eta',
        status: 'error',
        date: '2025-07-16',
        size: '145kb',
        owner: 'admin@gmail.com',
        number_img: 22,
        iso: 104,
        img_discription: 'ภาพถ่ายมาโครของส่วนประกอบอิเล็กทรอนิกส์',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
      {
        image: 'https://picsum.photos/seed/project1/400/300',
        name: 'Project Alpha',
        status: 'succeed',
        date: '2025-07-22',
        size: '150kb',
        owner: 'admin@gmail.com',
        number_img: 25,
        iso: 104,
        img_discription: 'ภาพถ่ายผลิตภัณฑ์สำหรับแคมเปญฤดูร้อน',
      },
      {
        image: 'https://picsum.photos/seed/project2/400/300',
        name: 'Project Beta',
        status: 'error',
        date: '2025-07-21',
        size: '110kb',
        owner: 'admin@gmail.com',
        number_img: 10,
        iso: 104,
        img_discription: 'ภาพถ่ายสถาปัตยกรรมภายในอาคารสำนักงาน',
      },
      {
        image: 'https://picsum.photos/seed/project3/400/300',
        name: 'Project Gamma',
        status: 'fix',
        date: '2025-07-20',
        size: '180kb',
        owner: 'admin@gmail.com',
        number_img: 40,
        iso: 104,
        img_discription: 'ภาพถ่ายบุคคลสำหรับโปรไฟล์ทีม',
      },
      {
        image: 'https://picsum.photos/seed/project4/400/300',
        name: 'Project Delta',
        status: 'async',
        date: '2025-07-19',
        size: '95kb',
        owner: 'admin@gmail.com',
        number_img: 18,
        iso: 104,
        img_discription: 'ภาพถ่ายทิวทัศน์จากโดรน',
      },
      {
        image: 'https://picsum.photos/seed/project5/400/300',
        name: 'Project Epsilon',
        status: 'succeed',
        date: '2025-07-18',
        size: '210kb',
        owner: 'admin@gmail.com',
        number_img: 55,
        iso: 104,
        img_discription: 'ภาพถ่ายอีเวนต์เปิดตัวสินค้าใหม่',
      },
      {
        image: 'https://picsum.photos/seed/project6/400/300',
        name: 'Project Zeta',
        status: 'succeed',
        date: '2025-07-17',
        size: '130kb',
        owner: 'admin@gmail.com',
        number_img: 30,
        iso: 104,
        img_discription: 'ภาพถ่ายอาหารสำหรับเมนูร้านอาหาร',
      },
      {
        image: 'https://picsum.photos/seed/project7/400/300',
        name: 'Project Eta',
        status: 'error',
        date: '2025-07-16',
        size: '145kb',
        owner: 'admin@gmail.com',
        number_img: 22,
        iso: 104,
        img_discription: 'ภาพถ่ายมาโครของส่วนประกอบอิเล็กทรอนิกส์',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
      {
        image: 'https://picsum.photos/seed/project1/400/300',
        name: 'Project Alpha',
        status: 'succeed',
        date: '2025-07-22',
        size: '150kb',
        owner: 'admin@gmail.com',
        number_img: 25,
        iso: 104,
        img_discription: 'ภาพถ่ายผลิตภัณฑ์สำหรับแคมเปญฤดูร้อน',
      },
      {
        image: 'https://picsum.photos/seed/project2/400/300',
        name: 'Project Beta',
        status: 'error',
        date: '2025-07-21',
        size: '110kb',
        owner: 'admin@gmail.com',
        number_img: 10,
        iso: 104,
        img_discription: 'ภาพถ่ายสถาปัตยกรรมภายในอาคารสำนักงาน',
      },
      {
        image: 'https://picsum.photos/seed/project3/400/300',
        name: 'Project Gamma',
        status: 'fix',
        date: '2025-07-20',
        size: '180kb',
        owner: 'admin@gmail.com',
        number_img: 40,
        iso: 104,
        img_discription: 'ภาพถ่ายบุคคลสำหรับโปรไฟล์ทีม',
      },
      {
        image: 'https://picsum.photos/seed/project4/400/300',
        name: 'Project Delta',
        status: 'async',
        date: '2025-07-19',
        size: '95kb',
        owner: 'admin@gmail.com',
        number_img: 18,
        iso: 104,
        img_discription: 'ภาพถ่ายทิวทัศน์จากโดรน',
      },
      {
        image: 'https://picsum.photos/seed/project5/400/300',
        name: 'Project Epsilon',
        status: 'succeed',
        date: '2025-07-18',
        size: '210kb',
        owner: 'admin@gmail.com',
        number_img: 55,
        iso: 104,
        img_discription: 'ภาพถ่ายอีเวนต์เปิดตัวสินค้าใหม่',
      },
      {
        image: 'https://picsum.photos/seed/project6/400/300',
        name: 'Project Zeta',
        status: 'succeed',
        date: '2025-07-17',
        size: '130kb',
        owner: 'admin@gmail.com',
        number_img: 30,
        iso: 104,
        img_discription: 'ภาพถ่ายอาหารสำหรับเมนูร้านอาหาร',
      },
      {
        image: 'https://picsum.photos/seed/project7/400/300',
        name: 'Project Eta',
        status: 'error',
        date: '2025-07-16',
        size: '145kb',
        owner: 'admin@gmail.com',
        number_img: 22,
        iso: 104,
        img_discription: 'ภาพถ่ายมาโครของส่วนประกอบอิเล็กทรอนิกส์',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
      {
        image: 'https://picsum.photos/seed/project1/400/300',
        name: 'Project Alpha',
        status: 'succeed',
        date: '2025-07-22',
        size: '150kb',
        owner: 'admin@gmail.com',
        number_img: 25,
        iso: 104,
        img_discription: 'ภาพถ่ายผลิตภัณฑ์สำหรับแคมเปญฤดูร้อน',
      },
      {
        image: 'https://picsum.photos/seed/project2/400/300',
        name: 'Project Beta',
        status: 'error',
        date: '2025-07-21',
        size: '110kb',
        owner: 'admin@gmail.com',
        number_img: 10,
        iso: 104,
        img_discription: 'ภาพถ่ายสถาปัตยกรรมภายในอาคารสำนักงาน',
      },
      {
        image: 'https://picsum.photos/seed/project3/400/300',
        name: 'Project Gamma',
        status: 'fix',
        date: '2025-07-20',
        size: '180kb',
        owner: 'admin@gmail.com',
        number_img: 40,
        iso: 104,
        img_discription: 'ภาพถ่ายบุคคลสำหรับโปรไฟล์ทีม',
      },
      {
        image: 'https://picsum.photos/seed/project4/400/300',
        name: 'Project Delta',
        status: 'async',
        date: '2025-07-19',
        size: '95kb',
        owner: 'admin@gmail.com',
        number_img: 18,
        iso: 104,
        img_discription: 'ภาพถ่ายทิวทัศน์จากโดรน',
      },
      {
        image: 'https://picsum.photos/seed/project5/400/300',
        name: 'Project Epsilon',
        status: 'succeed',
        date: '2025-07-18',
        size: '210kb',
        owner: 'admin@gmail.com',
        number_img: 55,
        iso: 104,
        img_discription: 'ภาพถ่ายอีเวนต์เปิดตัวสินค้าใหม่',
      },
      {
        image: 'https://picsum.photos/seed/project6/400/300',
        name: 'Project Zeta',
        status: 'succeed',
        date: '2025-07-17',
        size: '130kb',
        owner: 'admin@gmail.com',
        number_img: 30,
        iso: 104,
        img_discription: 'ภาพถ่ายอาหารสำหรับเมนูร้านอาหาร',
      },
      {
        image: 'https://picsum.photos/seed/project7/400/300',
        name: 'Project Eta',
        status: 'error',
        date: '2025-07-16',
        size: '145kb',
        owner: 'admin@gmail.com',
        number_img: 22,
        iso: 104,
        img_discription: 'ภาพถ่ายมาโครของส่วนประกอบอิเล็กทรอนิกส์',
      },
      {
        image: 'https://picsum.photos/seed/project8/400/300',
        name: 'Project Theta',
        status: 'fix',
        date: '2025-07-15',
        size: '160kb',
        owner: 'admin@gmail.com',
        number_img: 35,
        iso: 104,
        img_discription: 'ภาพถ่ายแฟชั่นเซ็ตสำหรับนิตยสาร',
      },
      {
        image: 'https://picsum.photos/seed/project9/400/300',
        name: 'Project Iota',
        status: 'async',
        date: '2025-07-14',
        size: '100kb',
        owner: 'admin@gmail.com',
        number_img: 15,
        iso: 104,
        img_discription: 'ภาพถ่ายแนวสตรีทในเมือง',
      },
      {
        image: 'https://picsum.photos/seed/project10/400/300',
        name: 'Project Kappa',
        status: 'succeed',
        date: '2025-07-13',
        size: '195kb',
        owner: 'admin@gmail.com',
        number_img: 48,
        iso: 104,
        img_discription: 'ภาพถ่ายสัตว์เลี้ยงในสตูดิโอ',
      },
    ]);
  }
}
